config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, 
    controllers: { sessions: "admin/sessions" }, 
    path: 'admin', 
    path_names: { 
      sign_in: 'login', 
      sign_out: 'logout' 
    }

  namespace :admin do 

    root 'projects#index'
    post 'position' => 'application#set_position', as: :set_position
    post 'positions' => 'application#set_positions', as: :set_positions

    resources :images, except: [:create, :update] do
      with_scope_level(:create) do
        post '(:type)/images(.:format)', to: 'images#create'
        patch '(:type)/images/:id(.:format)', to: 'images#update'
      end
    end

    resources :projects, param: :slug
    resources :pages, only: [:index, :edit, :update], param: :slug

  end
  
end

app/views/admin/pages/edit.slim
= form_for [:admin, @page], html: {}, url: admin_page_path(@page.slug) do |f|
  div.row.form-actions
    div.col-md-6.col-sm-offset-6    
      div.btn-group
        = f.submit 'Save', class: 'btn btn-default'

        button.btn.btn-default.dropdown-toggle type="button" data-toggle="dropdown"
          span.caret
          span.sr-only Toggle Dropdown
        ul.dropdown-menu.pull-right role="menu"
          li 
            a.save-edit href="#" Save and Edit
          li
            a href="#{admin_pages_path}" Cancel

  .row

    .col-sm-6

      .form-group
          = f.label :content, class: 'control-label'
          = f.text_area :content, class: 'form-control', rows: 10


    .col-sm-6

      .form-group
        = f.label :sidebar, class: 'control-label'
        = f.text_area :sidebar, class: 'form-control', rows: 10

      

app/views/admin/pages/index.slim
div.index-actions
  div.row

table.table.table-striped.table-hover
  thead
    tr
      th Title
      th Actions
  tbody
    - @pages.each_with_index do |page, i|
      tr
        td= page.title
        td.actions
          ul

            li
              a class="fa fa-pencil-square-o" data-toggle="tooltip" data-placement="top" title="Edit Page" href="#{edit_admin_page_path(page.slug)}"