config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, 
    controllers: { sessions: "admin/sessions" }, 
    path: 'admin', 
    path_names: { 
      sign_in: 'login', 
      sign_out: 'logout' 
    }

  namespace :admin do 

    root 'projects#index'
    post 'position' => 'application#set_position', as: :set_position
    post 'positions' => 'application#set_positions', as: :set_positions

    resources :images, except: [:create, :update] do
      with_scope_level(:create) do
        post '(:type)/images(.:format)', to: 'images#create'
        patch '(:type)/images/:id(.:format)', to: 'images#update'
      end
    end

    resources :projects, param: :slug
    resources :pages, only: [:index, :edit, :update], param: :slug

  end
  
end

app/models/project.rb
class Project < ActiveRecord::Base

  validates_presence_of :title, :feature, :body
  validates_uniqueness_of :title

  before_save :set_slug

  def set_slug
    self.slug = title.parameterize
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params

    if @project.save
      clear_cache
      redirect_to params[:edit] ? 
      edit_admin_project_path(@project) : admin_projects_path
    else
      flash.now[:errors] = @project.errors.full_messages
      render action: 'new'
    end
  end

  def index       
    @projects = Project.all
  end

  def edit
    @project = Project.find_by_slug params[:slug]
    add_breadcrumb @project.title.titleize, edit_admin_project_path(@project)
  end

  def update
    @project = Project.find_by_slug params[:slug]

    if @project.update_attributes(project_params)
      clear_cache
      redirect_to params[:edit] ? edit_admin_project_path(@project) : admin_projects_path
    else
      flash.now[:errors] = @project.errors.full_messages
      render action: 'edit'
    end
  end

  def destroy
    @project = Project.find_by_slug params[:slug]
    if @project.destroy
      redirect_to admin_projects_path
    else
      flash.now[:errors] = @project.errors.full_messages
      render action: 'edit'
    end
  end
  
  private

  def project_params
    params.require(:project).permit(:title, :description, :credits, :url, :feature, :body, :status)
  end

end

app/views/admin/projects/_form.slim
- url = @project.new_record? ? new_admin_project_path : admin_project_path(@project.slug)
= form_for [:admin, @project], html: {}, url: url do |f|
  div.row.form-actions
    div.col-md-6.col-sm-offset-6    
      div.btn-group
        = f.submit 'Save', class: 'btn btn-default'

        button.btn.btn-default.dropdown-toggle type="button" data-toggle="dropdown"
          span.caret
          span.sr-only Toggle Dropdown
        ul.dropdown-menu.pull-right role="menu"
          li 
            a.save-edit href="#" Save and Edit
          li
            a href="#{admin_projects_path}" Cancel
          - unless @project.new_record? 
            li.divider
            li= link_to 'Delete', admin_project_path(@project), method: :delete, 
              data: { confirm: "Are you sure you want to delete this project?" }

  .row
    .col-sm-6

      .form-group
        = f.label :status
        br
        div.radio-inline
          = f.label :public
          = f.radio_button :status, true
        div.radio-inline
          = f.label :private
          = f.radio_button :status, false

  .row

    .col-sm-6

      .form-group
        = f.label :title, class: 'control-label'
        = f.text_field :title, class: 'form-control'

      .form-group
          = f.label :description, class: 'control-label'
          = f.text_area :description, class: 'form-control', rows: 7


    .col-sm-6

      .form-group
        = f.label :url, class: 'control-label'
        = f.text_field :url, class: 'form-control'

      .form-group
        = f.label :credits, class: 'control-label'
        = f.text_area :credits, class: 'form-control', rows: 7


  .row.json-content
    div.form-group.col-sm-12
      = f.label :feature, 'Feature Images', class: 'control-label'
      = f.text_area :feature, class: 'image_json', data: { type: 'feature', blocklimit:1 }

  .row.json-content
    div.form-group.col-sm-12
      = f.label :body, 'Body Images', class: 'control-label'
      = f.text_area :body, class: 'image_json', data: { type: 'body' }
      

app/views/admin/projects/edit.slim
=render partial: 'form'

app/views/admin/projects/index.slim
div.index-actions
  div.row
    div.col-md-6.col-md-offset-6
      a type="button" class="btn btn-default" href="#{new_admin_project_path}"
        ="New Project"

.sortable-list data-class="project" data-constant="Project" data-submittable="true"
  table.table.table-striped.table-hover
    thead
      tr
        th Title
        th Status
        th Position
        th Actions
    tbody.sortable
      - @projects.each_with_index do |project, i|
        tr.sort-item data-id=project.id class="#{!project.status ? 'grayed' : ''}"
          td= project.title
          td= project.status ? 'Visible' : 'Hidden'
          td
            select.position
              - @projects.length.times do |c|
                option value=c selected=('selected' if c == i)
                  = c + 1
          td.actions
            ul

              li
                a class="fa fa-pencil-square-o" data-toggle="tooltip" data-placement="top" title="Edit Project" href="#{edit_admin_project_path(project)}"
              
              li
                a class="fa fa-arrows" data-toggle="tooltip" data-placement="top" title="Position Project" href="#"

= render partial: 'admin/shared/positioner_form'

app/views/admin/projects/new.slim
=render partial: 'form'