config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, 
    controllers: { sessions: "admin/sessions" }, 
    path: 'admin', 
    path_names: { 
      sign_in: 'login', 
      sign_out: 'logout' 
    }

  namespace :admin do 

    root 'projects#index'
    post 'position' => 'application#set_position', as: :set_position
    post 'positions' => 'application#set_positions', as: :set_positions

    resources :images, except: [:create, :update] do
      with_scope_level(:create) do
        post '(:type)/images(.:format)', to: 'images#create'
        patch '(:type)/images/:id(.:format)', to: 'images#update'
      end
    end

    resources :projects, param: :slug
    resources :pages, only: [:index, :edit, :update], param: :slug

  end
  
end

app/views/admin/shared/_footer.slim
footer

app/views/admin/shared/_grid_item_table.slim
.form-group
  label.control-label Grid Items
  .sortable-list data-class="grid_item" data-constant="GridItem" data-submittable="true"
    table.table.table-striped.table-hover
      thead
        tr
          th Thumb
          th Title
          th Status
          th Position
          th Actions
      tbody.sortable
        - grid_item_table.each_with_index do |grid_item, i|
          tr.sort-item data-id=grid_item.id class="#{!grid_item.status ? 'grayed' : ''}"
            td=image_tag(grid_item.image(:thumb), width: 80, height: 80)
            td=grid_item.plain_title
            td=grid_item.status ? 'Visible' : 'Hidden'
            td
              select.position
                - grid_item_table.length.times do |c|
                  option value=c selected=('selected' if c == i)
                    = c + 1

            td.actions
              ul
                li
                  - if params['controller'] == 'admin/pages'
                    - href = edit_admin_page_grid_item_path(grid_item.page, grid_item)
                  a class="fa fa-pencil-square-o" data-toggle="tooltip" data-placement="top" title="Edit Grid Item" href="#{href}"
                li
                  a class="fa fa-arrows" data-toggle="tooltip" data-placement="top" title="Position Grid Item" href="#"
            

app/views/admin/shared/_grid_margin_form_fields.slim
.row
  .col-sm-4
  .col-sm-4
    .form-group
      .input-group
        input.form-control type="text" name="#{prefix}[margins][top]" value=object.top_margin
        span.input-group-addon px

.row.margin-display-row
  .col-sm-4
    .form-group
      .input-group
        input.form-control type="text" name="#{prefix}[margins][left]" value=object.left_margin
        span.input-group-addon px

  .col-sm-4.margin-display
    .margin-outer
      .margin-inner

  .col-sm-4
    .form-group
      .input-group
        input.form-control type="text" name="#{prefix}[margins][right]" value=object.right_margin
        span.input-group-addon px

.row
  .col-sm-4
  .col-sm-4
    .form-group
      .input-group
        input.form-control type="text" name="#{prefix}[margins][bottom]" value=object.bottom_margin
        span.input-group-addon px

app/views/admin/shared/_header.slim
header
  nav class="main navbar navbar-default"
    div class="container"
      div class="navbar-header"
        button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav"
          span class="sr-only" Toggle navigation
          span class="icon-bar"
          span class="icon-bar"
          span class="icon-bar"
        a class="navbar-brand" href="#{admin_root_path}" Puffinstuff Admin
  
      div id="main-nav" class="collapse navbar-collapse"
        ul class="nav navbar-nav"

          li class="#{ 'active' if params[:controller] == 'admin/projects' }"
           = link_to "Projects", admin_projects_path

          li class="#{ 'active' if params[:controller] == 'admin/pages' }"
           = link_to "Pages", admin_pages_path

        ul class="nav navbar-nav navbar-right"
          li= link_to 'Log Out', destroy_admin_user_session_path, method: :delete        
    
  div id="breadcrumb"    
    div class="container"
      ol class="breadcrumb"    
        =render_breadcrumbs tag: :li, separator: ""
  
  div id="flash" 
    - if flash[:errors]
      div class="errors"
        div class="container"
          ul    
            - flash[:errors].each do |error|
              li=error.html_safe
    - if flash[:notices]
      div class="notice"
        div class="container"
          ul    
            - flash[:notices].each do |notice|
              li=notice.html_safe

app/views/admin/shared/_image_panel.slim
- form = local_assigns.fetch :form, nil
.panel.panel-default.admin-panel.image-panel
  
  .panel-heading
    .btn-group
      - attachments.each do |a|
        - title = a[:title] ? a[:title] : a[:name]
        - a[:styles].each_with_index do |style, index|
          - name = "#{a[:name]}_#{style}"
          button.btn.btn-default type="button" data-attachment="#{a[:name]}" data-variant="#{name}" tab-index="#{index+1}" =title
  
  .panel-body
    - attachments.each do |a|
      - a[:styles].each do |style|
        - name = "#{a[:name]}_#{style}"
        .image data-variant=name
          - if image_panel.send(a[:name]).file?
            = image_tag image_panel.send(a[:name], style)
          - else
            = "No image uploaded"

  - if form
    .panel-footer
      - attachments.each do |a|
        - title = a[:title] ? a[:title].titleize : a[:name].titleize
        .upload data-attachment="#{a[:name]}"
          = form.label a[:name].to_sym, image_panel.send(a[:name]).file? ? "Change #{title}" : "Upload #{title}"
          .row 
            .form-group.col-sm-6
              = form.file_field a[:name].to_sym
            - delete = "delete_#{a[:name]}".to_sym
            - if image_panel.respond_to? delete
              .form-group.col-sm-6
                = form.check_box delete
                = " Delete?"

app/views/admin/shared/_multilingual_panel.slim
div.panel.panel-default.admin-panel
  div.panel-heading
    div.btn-group
      - I18n.available_locales.each_with_index do |lang, index|
        button.btn.btn-default type="button" data-variant="#{lang}" tab-index="#{index+1}" =lang
  div.panel-body
    - I18n.available_locales.each_with_index do |lang, index|          
      - value = object.send(field, lang)
      - name = "#{object.class.name.underscore}[#{field}][#{lang}]"
      - id = "#{object.class.name.underscore}_#{field}_#{lang}"
      - data = {variant: "#{lang}"}
      
      - if type == 'textarea'
        = form.text_area field.to_sym, name: name, id: id, value: value, class: 'form-control', data: data
      - else
        = form.text_field field.to_sym, name: name, id: id, value: value, class: 'form-control', data: data

app/views/admin/shared/_pagination.slim
div.paginate
  .row
    .col-md-6.col-md-offset-3
      = paginate pagination

app/views/admin/shared/_positioner_form.slim
form class="position_form_sortable" action=admin_set_positions_path method="post"
  input type="hidden" name="start_index" value=start_index
  input type="hidden" name="positions"
  input type="hidden" name="klass"
  input type="hidden" name="page" value=params[:page]
  input type="hidden" name="authenticity_token" value=form_authenticity_token
  
form class="position_form_select" action=admin_set_position_path method="post"
  input type="hidden" name="id"
  input type="hidden" name="section"
  input type="hidden" name="position"
  input type="hidden" name="klass"
  input type="hidden" name="page" value=params[:page]
  input type="hidden" name="authenticity_token" value=form_authenticity_token

app/views/admin/shared/_sortable_list.slim
- thumbnail_template = local_assigns.fetch :thumbnail_template, false
- item_edit_path = local_assigns.fetch :item_edit_path, false
- item_edit_method = local_assigns.fetch :item_edit_method, false
- add_remove = local_assigns.fetch :add_remove, false
- position_scope_name = local_assigns.fetch :position_scope_name, false
- position_scope = local_assigns.fetch :position_scope, false
- name_field = local_assigns.fetch :name_field, 'name'

- template = (render partial: 'admin/shared/sortable_list_item', locals: {item: template_source, thumbnail_template: thumbnail_template, item_edit_path: item_edit_path, item_edit_method: item_edit_method, add_remove: add_remove, name_field: name_field}).encode

.panel.panel-default.admin-panel.sortable-list data-class=klass.to_s.singularize data-parent=parent data-template=template data-submittable="false"

  .panel-heading

    - if defined? new_item_path
      a.btn.btn-default.pull-right href="#{new_item_path}"
        = "Add #{klass.capitalize}"

    - if add_remove
      .select-list.pull-right
        select.sortable-add-select.form-control
          - addable_items.each do |item|
            - thumbnail = thumbnail_template ? render(partial: thumbnail_template, local: {item: item}) : image_tag(item.thumbnail_image)
            option value=item.id disabled=existing_items.include?(item) data-thumbnail=thumbnail.encode data-caption=item.send(name_field) data-id=item.id
              = item.send(name_field)
        a.btn.btn-default.sortable-add-button href="#"
          = "Add"

  .panel-body
    .row.list.sortable

      .no-items class="#{(existing_items.length > 0) ? 'hide' : ''}"
        = "Nothing to see here"

      - existing_items.each do |item|

        = render partial: 'admin/shared/sortable_list_item', locals: {item: item, thumbnail_template: thumbnail_template, item_edit_path: item_edit_path, item_edit_method: item_edit_method, add_remove: add_remove, name_field: name_field}
  
  
  input.sortable-positions name="#{parent}[#{klass.to_s.singularize}_positions][]" value="" type="hidden"

  - if position_scope
    input name="#{parent}[#{klass.to_s.singularize}_position_scopes][]" value=position_scope type="hidden"

  - if position_scope_name
    input name="#{parent}[#{klass.to_s.singularize}_position_scope_name]" value=position_scope_name type="hidden"
  .sortable-id-list

app/views/admin/shared/_sortable_list_item.slim
.sort-item.col-sm-3.col-md-2 data-id=item.id class="#{item.respond_to?('status') && !item.status ? 'grayed' : ''}"
  
  .thumbnail
    .item-thumbnail
      - thumbnail = thumbnail_template ? render(partial: thumbnail_template, locals: {item: item}) : image_tag(item.thumbnail_image)
      = thumbnail

    .caption
      p.item-caption= item.send(name_field)

      .btn-group

        - if add_remove
          a.btn.btn-default.remove-button type="button" href="#"
            = "Remove"

        - if item_edit_path
          - href = item.new_record? ? item_edit_path : URI::decode(item_edit_path).gsub('[item_id]', item.id.to_s)
        - elsif item_edit_method
          - href = send(item_edit_method, item)
        - else 
          - href = false
        
        - if href
          a.btn.btn-default.edit-button type="button" href=href
            = "Edit"